package com.example.core.color

/**
 * What the strip actually emits for a commanded colour byte.
 *
 * GENERATED by `tools/calibration/emit_strip_response.py` from
 * `tools/calibration/derived/device_model.json`. Do not hand-edit - regenerate it.
 *
 * ## What this is
 *
 * [LIGHT_FOR_BYTE] holds the measured light for every byte 0-255, normalised so byte 255 is 1.0.
 * The strip is strongly front-loaded: **half its total output arrives by byte 67**, byte 32 is
 * already at 26%, and bytes 0 and 1 emit nothing at all. So byte-space reasoning is
 * misleading everywhere and badly wrong near black, where one byte is a 12% change in
 * emitted light at byte 14 and 29% at byte 7.
 *
 * ## How far to trust it
 *
 * Relative camera light, not photometry - ratios within the table mean something, a single value in
 * physical units does not. Confidence is `single`: the run measured every byte at three
 * exposures on the premise that they would confirm each other, and they do not. Only above byte
 * 137 are two exposures within 25%. **Below byte 8 the table is a lower bound on the light
 * rather than a measurement of it** - good for shape, not for a specific value. Do not build
 * anything that needs a low-byte number to better than a factor of two.
 *
 * Full reasoning: `tools/calibration/analyse_ramp_x3.py`.
 */
object StripResponse {

    /** Measured light emitted for each commanded byte, 0.0-1.0, normalised to byte 255. */
    val LIGHT_FOR_BYTE: DoubleArray = doubleArrayOf(
        0.0, 0.0, 0.0005729290, 0.002464310, 0.006027690, 0.01133250, 0.01804590, 0.02500920,  // 0-7
        0.03229460, 0.04010610, 0.04784790, 0.05614350, 0.06556710, 0.07563830, 0.08452470, 0.09425950,  // 8-15
        0.1041710, 0.114440, 0.1249340, 0.1359040, 0.145630, 0.1568390, 0.1656090, 0.1754810,  // 16-23
        0.1848830, 0.1947610, 0.204020, 0.2138710, 0.2222690, 0.2338990, 0.2430410, 0.2545780,  // 24-31
        0.262440, 0.2734120, 0.2824350, 0.2909070, 0.2997810, 0.3081050, 0.3163620, 0.326140,  // 32-39
        0.3340040, 0.3416350, 0.3489220, 0.3554390, 0.3613170, 0.3701760, 0.3748740, 0.3824140,  // 40-47
        0.3886590, 0.395540, 0.4035390, 0.4087720, 0.4148120, 0.4213310, 0.4279590, 0.4347230,  // 48-55
        0.4405410, 0.4429590, 0.4487780, 0.4561880, 0.4627280, 0.4692650, 0.4735110, 0.4780010,  // 56-63
        0.483530, 0.4884690, 0.4959020, 0.5037430, 0.5092340, 0.5131170, 0.517830, 0.5243030,  // 64-71
        0.5298790, 0.5348870, 0.5403020, 0.546330, 0.5483090, 0.5552640, 0.561110, 0.5671020,  // 72-79
        0.5716430, 0.5763840, 0.5783410, 0.5867760, 0.5924680, 0.5972990, 0.599420, 0.6041310,  // 80-87
        0.6089370, 0.6167890, 0.6186720, 0.6214110, 0.6272230, 0.62830, 0.6365540, 0.6418010,  // 88-95
        0.6413950, 0.6481690, 0.6508620, 0.6571220, 0.6599930, 0.6625940, 0.6664320, 0.6665160,  // 96-103
        0.6719270, 0.6737010, 0.6803710, 0.6832080, 0.6871990, 0.6914510, 0.6924990, 0.6956720,  // 104-111
        0.6961160, 0.7035920, 0.7015070, 0.7060080, 0.7084870, 0.7136430, 0.7207280, 0.7257910,  // 112-119
        0.7294320, 0.7304690, 0.7346250, 0.7340240, 0.7396490, 0.7420460, 0.7426360, 0.7471330,  // 120-127
        0.7490710, 0.7517420, 0.7533340, 0.7563740, 0.7585930, 0.757280, 0.7618650, 0.7669140,  // 128-135
        0.7651150, 0.7708310, 0.7755250, 0.7759140, 0.7781880, 0.78180, 0.7823140, 0.7883710,  // 136-143
        0.7871130, 0.7908320, 0.7933860, 0.7963440, 0.7952280, 0.8005750, 0.8003490, 0.8061850,  // 144-151
        0.8086750, 0.8115650, 0.8140280, 0.8150650, 0.8176850, 0.8210580, 0.8198360, 0.8251080,  // 152-159
        0.823210, 0.8285120, 0.8296090, 0.8321540, 0.8356710, 0.838310, 0.840480, 0.8400620,  // 160-167
        0.8423160, 0.8423730, 0.8453830, 0.8492580, 0.8527990, 0.857070, 0.8575950, 0.8609230,  // 168-175
        0.8620960, 0.8631710, 0.8623250, 0.8659970, 0.8668540, 0.8692310, 0.8700660, 0.8744210,  // 176-183
        0.8758760, 0.8753360, 0.8778010, 0.8782610, 0.8831570, 0.8846060, 0.8886940, 0.8894660,  // 184-191
        0.8918080, 0.8942130, 0.8923580, 0.8974640, 0.899090, 0.9004010, 0.8980420, 0.9038090,  // 192-199
        0.9064110, 0.9085180, 0.9089540, 0.9125580, 0.915680, 0.9179340, 0.9153820, 0.9201640,  // 200-207
        0.9195260, 0.922490, 0.9244310, 0.9314220, 0.9315470, 0.9347840, 0.934320, 0.9360970,  // 208-215
        0.9374330, 0.9402920, 0.9402490, 0.9414070, 0.9457360, 0.9440660, 0.9508570, 0.9504940,  // 216-223
        0.9474780, 0.9526060, 0.9547880, 0.9568130, 0.9597370, 0.9604260, 0.9534820, 0.9548250,  // 224-231
        0.9614820, 0.9662340, 0.9682480, 0.9738810, 0.9692380, 0.9702410, 0.9715530, 0.9733030,  // 232-239
        0.9813770, 0.9799850, 0.9802540, 0.9792690, 0.9861510, 0.9870670, 0.9828450, 0.9879410,  // 240-247
        0.9862360, 0.9899590, 0.9903870, 0.998680, 0.9974930, 0.9929050, 0.998030, 1.0,  // 248-255
    )

    /** Light emitted for a commanded byte. Clamped, so callers need not range-check. */
    fun lightForByte(b: Int): Double = LIGHT_FOR_BYTE[b.coerceIn(0, 255)]

    /**
     * The byte whose emitted light is closest to [light].
     *
     * The inverse of [lightForByte], by search rather than by a fitted exponent - no single power
     * fits this curve, and the whole point of measuring it was to stop guessing one. Ties go to the
     * lower byte, so asking for more light never gives less.
     */
    fun byteForLight(light: Double): Int {
        val target = light.coerceIn(0.0, 1.0)
        var best = 0
        var bestErr = Double.MAX_VALUE
        for (b in 0..255) {
            val err = kotlin.math.abs(LIGHT_FOR_BYTE[b] - target)
            if (err < bestErr) {
                bestErr = err
                best = b
            }
        }
        return best
    }

    /**
     * How much the emitted light changes for one more byte at [b], as a fraction of full output.
     *
     * This is the number that decides whether a dark scene can be faded smoothly: where one byte is
     * a large step, no amount of smoothing upstream can command anything between two adjacent
     * bytes, and only dithering across successive writes can.
     */
    fun lightStepAtByte(b: Int): Double {
        val lo = lightForByte(b)
        val hi = lightForByte(b + 1)
        return hi - lo
    }
}
