package com.example.core.perception.lab

/**
 * What ambiance would have commanded, for one stretch of film, under two rules.
 *
 * GENERATED by `AmbianceVideoBench.emit lab traces` - do not hand-edit. Regenerate with:
 *
 * ```
 * python tools/ambiance-bench/fetch.py --out <dir>
 * ./gradlew :app:testDebugUnitTest --tests '*AmbianceVideoBench*' \\
 *     -Dambiance.frames=<dir> -Dambiance.traces=<path to this file>
 * ```
 *
 * ## What the two arms are
 *
 * `shipped` is the pipeline as it stands. `symmetricFall` differs in exactly one line: the
 * smoother stops using a larger alpha when the picture gets darker than the strip currently
 * is. At the shipped settings that asymmetry makes falls about 1.8x faster than rises, which
 * on noisy dark content rectifies noise into a sawtooth - the bench measures 36% more
 * emitted-level reversals with it than without, and multi-level jumps on 13% of transitions
 * against 1%.
 *
 * Both arms are computed from the **same frames**, so they carry the same number of writes at
 * the same moments and cannot be told apart by cadence - the control blocks 3 and 4 needed.
 *
 * ## What these are not
 *
 * They are a recording, not a live capture. Nothing here decides whether the change is
 * better; that is what asking Joe is for. The bench only says the two differ, and where.
 */
object AmbianceTraces {

    /** One excerpt, the same moment rendered by both rules. Values are commanded RGB bytes. */
    data class AmbianceTracePair(
        val id: String,
        val stepMs: Long,
        val shipped: List<Int>,
        val symmetricFall: List<Int>
    )


    /**
     * dark_a: the worst 4000ms of the clip under the shipped rule.
     *
     * Emitted-level reversals across this window at 22% brightness:
     * shipped 46, symmetric 36.
     */
    val DARK_A = AmbianceTracePair(
        id = "dark_a",
        stepMs = 50L,
        shipped = listOf(
            68, 48, 32, 68, 48, 32, 68, 48, 32, 68, 48, 32, 68, 49, 34, 67, 50, 35,
            67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36,
            67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36, 67, 50, 36,
            67, 50, 36, 67, 50, 36, 68, 52, 39, 68, 52, 40, 68, 53, 40, 68, 53, 41,
            68, 53, 41, 68, 53, 41, 68, 53, 41, 68, 53, 41, 68, 53, 41, 68, 53, 41,
            68, 53, 41, 69, 56, 44, 69, 57, 46, 69, 57, 46, 70, 59, 49, 71, 60, 50,
            68, 57, 47, 67, 56, 46, 68, 58, 48, 67, 57, 48, 65, 54, 45, 63, 53, 43,
            66, 56, 47, 65, 55, 46, 65, 54, 45, 66, 56, 47, 69, 59, 51, 69, 59, 49,
            68, 58, 49, 70, 61, 52, 71, 63, 54, 68, 59, 50, 67, 57, 49, 68, 59, 50,
            66, 57, 49, 64, 54, 45, 64, 54, 46, 68, 58, 50, 66, 55, 47, 65, 54, 45,
            69, 58, 50, 70, 60, 52, 67, 57, 48, 69, 58, 49, 72, 62, 53, 71, 60, 50,
            66, 54, 44, 65, 52, 43, 66, 54, 44, 63, 51, 41, 62, 49, 40, 65, 54, 45,
            71, 60, 50, 68, 57, 47, 68, 56, 47, 73, 61, 52, 75, 64, 54, 71, 60, 50,
            72, 61, 51, 74, 64, 55,
        ),
        symmetricFall = listOf(
            66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34,
            66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34,
            66, 48, 34, 66, 48, 34, 66, 48, 34, 66, 48, 34, 67, 49, 37, 67, 50, 38,
            67, 50, 38, 67, 50, 39, 67, 52, 41, 67, 53, 42, 67, 54, 42, 67, 54, 43,
            67, 54, 43, 67, 54, 43, 67, 54, 43, 67, 54, 43, 67, 54, 43, 67, 54, 43,
            67, 54, 43, 68, 56, 45, 69, 57, 46, 69, 58, 47, 70, 59, 49, 71, 60, 51,
            70, 59, 49, 68, 58, 48, 69, 59, 49, 69, 59, 49, 68, 57, 48, 67, 56, 47,
            69, 60, 50, 68, 59, 50, 67, 57, 48, 68, 58, 50, 71, 61, 52, 70, 61, 52,
            70, 62, 52, 72, 64, 54, 73, 65, 55, 72, 63, 54, 70, 60, 52, 70, 61, 52,
            69, 59, 51, 67, 57, 49, 68, 58, 50, 70, 60, 52, 70, 60, 51, 68, 58, 50,
            71, 61, 53, 73, 63, 55, 71, 61, 53, 72, 62, 54, 75, 65, 57, 75, 64, 56,
            72, 60, 52, 70, 58, 50, 70, 59, 50, 68, 57, 48, 66, 54, 45, 69, 58, 48,
            73, 63, 53, 73, 62, 52, 72, 61, 51, 76, 65, 55, 77, 67, 57, 75, 65, 55,
            77, 66, 57, 78, 68, 59,
        )
    )

    /**
     * dark_b: the worst 4000ms of the clip under the shipped rule.
     *
     * Emitted-level reversals across this window at 22% brightness:
     * shipped 107, symmetric 59.
     */
    val DARK_B = AmbianceTracePair(
        id = "dark_b",
        stepMs = 50L,
        shipped = listOf(
            64, 56, 46, 71, 63, 53, 68, 59, 49, 66, 56, 46, 70, 61, 51, 75, 66, 56,
            71, 63, 53, 64, 57, 47, 67, 60, 50, 69, 61, 52, 64, 57, 47, 64, 57, 47,
            68, 60, 50, 64, 56, 46, 62, 54, 44, 67, 59, 49, 73, 66, 56, 68, 61, 51,
            68, 61, 51, 74, 66, 56, 76, 69, 59, 71, 63, 53, 73, 65, 55, 76, 69, 58,
            72, 64, 54, 67, 59, 49, 68, 60, 50, 68, 61, 51, 64, 55, 45, 64, 56, 46,
            69, 61, 51, 73, 65, 55, 70, 63, 53, 72, 65, 55, 76, 69, 59, 73, 65, 56,
            68, 59, 50, 70, 62, 52, 72, 64, 54, 67, 58, 48, 66, 57, 47, 70, 61, 51,
            67, 58, 49, 66, 56, 47, 69, 59, 51, 75, 65, 56, 74, 65, 55, 73, 65, 55,
            76, 68, 58, 78, 70, 60, 72, 63, 54, 68, 59, 51, 70, 62, 52, 68, 59, 49,
            65, 56, 46, 68, 59, 49, 72, 64, 54, 68, 59, 50, 67, 58, 49, 70, 62, 53,
            73, 65, 55, 68, 61, 51, 69, 61, 53, 73, 65, 57, 71, 63, 54, 66, 57, 49,
            66, 58, 49, 67, 58, 50, 63, 54, 45, 61, 53, 44, 65, 57, 48, 70, 62, 53,
            67, 59, 50, 67, 60, 51, 70, 63, 55, 70, 63, 55, 64, 57, 49, 65, 58, 50,
            67, 60, 52, 63, 56, 48,
        ),
        symmetricFall = listOf(
            72, 64, 54, 77, 69, 59, 75, 66, 56, 73, 65, 55, 76, 68, 58, 79, 71, 61,
            77, 70, 60, 73, 65, 56, 75, 68, 58, 75, 68, 58, 72, 64, 55, 71, 64, 54,
            73, 65, 56, 71, 63, 53, 68, 61, 51, 72, 64, 55, 77, 69, 59, 75, 68, 58,
            74, 67, 57, 78, 71, 61, 79, 72, 61, 76, 68, 58, 78, 70, 60, 81, 73, 63,
            78, 70, 60, 75, 67, 57, 75, 67, 57, 75, 67, 57, 72, 63, 53, 72, 63, 53,
            75, 67, 57, 76, 69, 58, 75, 68, 57, 76, 69, 59, 79, 71, 61, 78, 70, 60,
            74, 67, 57, 76, 68, 59, 77, 69, 60, 74, 66, 57, 73, 65, 55, 76, 68, 58,
            74, 66, 56, 72, 63, 53, 74, 64, 54, 78, 69, 58, 78, 70, 59, 78, 70, 60,
            80, 72, 62, 81, 73, 63, 78, 70, 60, 75, 67, 57, 75, 67, 58, 74, 66, 56,
            71, 62, 53, 73, 64, 54, 76, 68, 58, 74, 66, 56, 73, 65, 55, 75, 67, 58,
            76, 68, 59, 74, 66, 56, 74, 66, 57, 77, 69, 60, 76, 68, 59, 73, 65, 56,
            72, 64, 55, 72, 64, 55, 69, 61, 52, 68, 60, 51, 70, 62, 54, 74, 66, 57,
            72, 64, 55, 72, 65, 56, 74, 67, 59, 74, 67, 58, 71, 63, 54, 71, 64, 56,
            72, 65, 56, 69, 62, 54,
        )
    )

    /** Every pair, in the order a block should offer them. */
    val ALL = listOf(DARK_A, DARK_B)
}
