#!/usr/bin/env python3
"""Put the measured byte-to-light curve where the app can read it.

    python tools/calibration/emit_strip_response.py

Writes app/src/main/java/com/example/core/color/StripResponse.kt from
derived/device_model.json. The app cannot read the JSON - it is a tools artifact, not an asset -
and hand-copying 256 numbers is exactly the kind of thing that goes stale silently. Regenerate
this whenever build_model.py runs.

The generated file carries the same caveats the model does, because a LUT with its provenance
stripped off is indistinguishable from a guess.
"""
import json, os, textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
MODEL = os.path.join(HERE, "derived", "device_model.json")
OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "app", "src", "main", "java", "com", "example",
                 "core", "color", "StripResponse.kt")
)

HEADER = '''package com.example.core.color

/**
 * What the strip actually emits for a commanded colour byte.
 *
 * GENERATED by `tools/calibration/emit_strip_response.py` from
 * `tools/calibration/derived/device_model.json`. Do not hand-edit - regenerate it.
 *
 * ## What this is
 *
 * [LIGHT_FOR_BYTE] holds the measured light for every byte 0-255, normalised so byte 255 is 1.0.
 * The strip is strongly front-loaded: **half its total output arrives by byte %(half)d**, byte 32 is
 * already at %(b32).0f%%, and bytes 0 and 1 emit nothing at all. So byte-space reasoning is
 * misleading everywhere and badly wrong near black, where one byte is a %(step14).0f%% change in
 * emitted light at byte 14 and %(step7).0f%% at byte 7.
 *
 * ## How far to trust it
 *
 * Relative camera light, not photometry - ratios within the table mean something, a single value in
 * physical units does not. Confidence is `%(confidence)s`: the run measured every byte at three
 * exposures on the premise that they would confirm each other, and they do not. Only above byte
 * %(agree_lo)d are two exposures within 25%%. **Below byte 8 the table is a lower bound on the light
 * rather than a measurement of it** - good for shape, not for a specific value. Do not build
 * anything that needs a low-byte number to better than a factor of two.
 *
 * Full reasoning: `tools/calibration/analyse_ramp_x3.py`.
 */
object StripResponse {

    /** Measured light emitted for each commanded byte, 0.0-1.0, normalised to byte 255. */
    val LIGHT_FOR_BYTE: DoubleArray = doubleArrayOf(
%(table)s
    )

    /** Light emitted for a commanded byte. Clamped, so callers need not range-check. */
    fun lightForByte(b: Int): Double = LIGHT_FOR_BYTE[b.coerceIn(0, 255)]

    /**
     * The byte whose emitted light is closest to [light].
     *
     * The inverse of [lightForByte], by search rather than by a fitted exponent - no single power
     * fits this curve, and the whole point of measuring it was to stop guessing one. Ties go to the
     * lower byte, so asking for more light never gives less.
     */
    fun byteForLight(light: Double): Int {
        val target = light.coerceIn(0.0, 1.0)
        var best = 0
        var bestErr = Double.MAX_VALUE
        for (b in 0..255) {
            val err = kotlin.math.abs(LIGHT_FOR_BYTE[b] - target)
            if (err < bestErr) {
                bestErr = err
                best = b
            }
        }
        return best
    }

    /**
     * How much the emitted light changes for one more byte at [b], as a fraction of full output.
     *
     * This is the number that decides whether a dark scene can be faded smoothly: where one byte is
     * a large step, no amount of smoothing upstream can command anything between two adjacent
     * bytes, and only dithering across successive writes can.
     */
    fun lightStepAtByte(b: Int): Double {
        val lo = lightForByte(b)
        val hi = lightForByte(b + 1)
        return hi - lo
    }
}
'''


def main():
    with open(MODEL) as f:
        model = json.load(f)
    r = model["colour_byte_to_light"]
    lut = r["lut"]
    rowsize = 8
    lines = []
    for i in range(0, 256, rowsize):
        # Always a decimal point: Kotlin reads a bare `0` as Int, and a DoubleArray literal of
        # mixed Int/Double does not compile.
        chunk = ", ".join(f"{float(v):.10f}".rstrip("0") + "0" for v in lut[i:i + rowsize])
        lines.append(f"        {chunk},  // {i}-{i + rowsize - 1}")
    table = "\n".join(lines).rstrip(",")

    body = HEADER % {
        "table": table,
        "half": r["half_output_reached_at_byte"],
        "b32": lut[32] * 100,
        "step14": (lut[15] - lut[14]) / lut[14] * 100,
        "step7": (lut[8] - lut[7]) / lut[7] * 100,
        "confidence": r["confidence"],
        "agree_lo": r["exposures_disagree"]["bytes_within_25_pct"][0],
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write(body)
    print(f"StripResponse.kt: 256 entries, half output at byte {r['half_output_reached_at_byte']}")


if __name__ == "__main__":
    main()
